export const products = [
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone XL',
    price: 799,
    description: 'Appleが開発したProのカメラシステムが、かつてないほど大きく進化。より多くのディテールをとらえる新次元のハードウェア。写真撮影や映画制作に新しい技術をもたらす極めて賢いソフトウェア。そのすべてを動かす信じられないほど速いチップを搭載。撮影の常識が一変します。',
    Heading1: 'サンプルテキスト1',
    Heading2: 'サンプルテキスト2',
    Heading3: 'サンプルテキスト3',
    headingtext1: 'サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト',
    headingtext2: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    headingtext3: 'ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Mini',
    price: 600,
    description: 'Appleが開発したProのカメラシステムが、かつてないほど大きく進化。より多くのディテールをとらえる新次元のハードウェア。写真撮影や映画制作に新しい技術をもたらす極めて賢いソフトウェア。そのすべてを動かす信じられないほど速いチップを搭載。撮影の常識が一変します。',
    Heading1: 'サンプルテキスト1',
    Heading2: 'サンプルテキスト2',
    Heading3: 'サンプルテキスト3',
    headingtext1: 'サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト',
    headingtext2: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    headingtext3: 'ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone St',
    price: 500,
    description: 'Appleが開発したProのカメラシステムが、かつてないほど大きく進化。より多くのディテールをとらえる新次元のハードウェア。写真撮影や映画制作に新しい技術をもたらす極めて賢いソフトウェア。そのすべてを動かす信じられないほど速いチップを搭載。撮影の常識が一変します。',
    Heading1: 'サンプルテキスト1',
    Heading2: 'サンプルテキスト2',
    Heading3: 'サンプルテキスト3',
    headingtext1: 'サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト',
    headingtext2: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    headingtext3: 'ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Sp',
    price: 600,
    description: 'Appleが開発したProのカメラシステムが、かつてないほど大きく進化。より多くのディテールをとらえる新次元のハードウェア。写真撮影や映画制作に新しい技術をもたらす極めて賢いソフトウェア。そのすべてを動かす信じられないほど速いチップを搭載。撮影の常識が一変します。',
    Heading1: 'サンプルテキスト1',
    Heading2: 'サンプルテキスト2',
    Heading3: 'サンプルテキスト3',
    headingtext1: 'サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト　サンプルテキスト',
    headingtext2: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    headingtext3: 'ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ　ああああああ',
  }
];